#1 ExtraCredit 1
franciscovilchezv/platform-based-development pull request #10
Opened 2021-12-07 11:56 UTC by PedroDominguezUTEC

Cambios en el homework ExtraCredit 2:
- yo también considero que la entrega del proyecto debería ser el 16 para así tener más tiempo para exponer, pero revisando el anexo del curso la entrega está programada para el 21 (https://i.imgur.com/56wi8vz.png). Se realiza un pull request de los cambios en caso sea necesario.
- Anexo: https://utec.instructure.com/courses/7441/files/1232555?module_item_id=624046

Asimismo se corrigen los siguientes errores ortográficos:

- se corrige error ortográfico de la palabra "desarrollo" en la línea 12.
- se corrige error ortográfico de la palabra "cámara" en la línea 26.
- se añade punto aparte en la línea 23.
- se corrige error ortográfico de la palabra "integrantes" en la línea 53.
- se corrige error ortográfico de la palabra "solo" en la línea 76.
(https://www.rae.es/espanol-al-dia/el-adverbio-solo-y-los-pronombres-demostrativos-sin-tilde)
- se corrige error ortográfico de la palabra "detendrá" en la línea 26.

2021-12-10 12:15 UTC, franciscovilchezv requested changes

2021-12-10 12:15 UTC, franciscovilchezv commented on Project/Project2/README.md
> +*La autocalificación grupal debe ser subida a más tardar el 21 de diciembre a las 23:59pm.* De lo contrario, usted no obtendrá nota alguna por el trabajo.
saa

2021-12-10 12:15 UTC, franciscovilchezv commented on Project/Project2/README.md
> +El equipo (uno o más representantes) presentará el proyecto el día **21 de diciembre**.
saa

2021-12-10 12:29 UTC, PedroDominguezUTEC commented on Project/Project2/README.md
> +*Dicho link debe ser subido a más tardar el 21 de diciembre a las 23:59pm*
done

2021-12-10 12:29 UTC, PedroDominguezUTEC commented on Project/Project2/README.md
> +*La autocalificación grupal debe ser subida a más tardar el 21 de diciembre a las 23:59pm.* De lo contrario, usted no obtendrá nota alguna por el trabajo.
done

2021-12-10 12:29 UTC, PedroDominguezUTEC commented on Project/Project2/README.md
> +El equipo (uno o más representantes) presentará el proyecto el día **21 de diciembre**.
se corrige el 16 por 17, ya que el viernes cae 17 pero la entrega es el 16

2021-12-10 17:44 UTC, franciscovilchezv approved these changes

2021-12-10 17:45 UTC, merged

2021-12-20 18:22 UTC, franciscovilchezv commented
+1 Proy1 Done